### ISSUE TITLE
build script

### ISSUE THREAD

**Issue by StoneCypher** [codemirror/lang-example#13]
Idiomatically and for CI, node modules should have an `npm build` which [does the thing](https://www.youtube.com/watch?v=mofRHlO1E_A&t=14s), because your users and all users are Bolin and don't read instructions, and don't know what to do

I know, nobody watches Korra and that metaphor definitely won't make sense

Users want to just `npm run build` and have it go `vroom` *before* they understand, so they can make sure it works (you know, does the, the, does the thing)

![](https://64.media.tumblr.com/b28c11d91f1f05d252b839cef0812f82/tumblr_mwzmy7UNKq1rss05ao4_250.gif)

Submitting fix PR

**Comment by marijnh** [comment]
There's all kinds of users, I guess, but the code will already have been built by the prepare script on install, so I don't really see this as a necessary addition.
