### ISSUE TITLE
.gitignore should not exclude package-lock.json

### ISSUE THREAD

**Issue by StoneCypher** [codemirror/lang-example#15]
Your tooling is excellent

One small point: package-lock should be in the repo, for three reasons.

1) This is how supply chain attacks can be investigated and prevented
2) A ci/cd path needs package.lock to do its installs; otherwise if it creates one on the spot it's not testing code as committed, but code as would have been created at any given time, and is subject to library drift
3) Several code scanners eg snyk treat it as positive signal and rank upwards for it

This PR removes package-lock from .gitignore.  A subsequent PR will add an actual package lockfile, so that if you decide you want to do that yourself you can merge this, but if you don't want to be bothered you can just merge both.

**Comment by marijnh** [comment]
I know what package lock does, I don't want it in this repository because I'm not going to keep it up to date.
