### ISSUE TITLE
Use @rollup/plugin-typescript

### ISSUE THREAD

**Issue by LeoDog896** [codemirror/lang-example#19]
[rollup-plugin-ts](https://www.npmjs.com/package/rollup-plugin-ts) is the unnoficial typescript plugin, versus [@rollup/plugin-typescript](https://www.npmjs.com/package/@rollup/plugin-typescript).

**Comment by marijnh** [comment]
Is there any concrete problem switching would solve?

**Comment by LeoDog896** [comment]
Nope, they both do essentially the same thing. I don't mind this for a set library, but for a template, it feels weird not to use the official version, however, given that, then I'll take it as not planned.
